CREATE TABLE poll (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_id BIGINT NOT NULL,
    title VARCHAR(200) NOT NULL,
    description TEXT,
    poll_type VARCHAR(20) NOT NULL,
    max_selections INTEGER NOT NULL CHECK (max_selections > 0),
    status VARCHAR(20) NOT NULL CHECK (status IN ('SCHEDULED', 'OPEN', 'PAUSED', 'CLOSED')),
    starts_at TIMESTAMPTZ NOT NULL,
    ends_at TIMESTAMPTZ NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CHECK (starts_at < ends_at)
);

CREATE INDEX idx_poll_status_ends_at ON poll (status, ends_at);

CREATE TABLE poll_option (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    poll_id BIGINT NOT NULL REFERENCES poll (id) ON DELETE CASCADE,
    name VARCHAR(100) NOT NULL,
    image_url TEXT,
    team VARCHAR(100),
    display_order INTEGER NOT NULL
);
