CREATE TABLE ballot (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    poll_id BIGINT NOT NULL REFERENCES poll (id) ON DELETE CASCADE,
    voter_key VARCHAR(64) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_ballot_poll_voter UNIQUE (poll_id, voter_key)
);

CREATE TABLE ballot_selection (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ballot_id BIGINT NOT NULL REFERENCES ballot (id) ON DELETE CASCADE,
    option_id BIGINT NOT NULL REFERENCES poll_option (id),
    CONSTRAINT uq_ballot_selection_ballot_option UNIQUE (ballot_id, option_id)
);

CREATE INDEX idx_ballot_selection_option ON ballot_selection (option_id);
