CREATE TABLE idempotency_request (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    voter_key VARCHAR(64) NOT NULL,
    poll_id BIGINT NOT NULL REFERENCES poll (id) ON DELETE CASCADE,
    idempotency_key UUID NOT NULL,
    request_hash CHAR(64) NOT NULL,
    response_body JSONB,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_idempotency_request UNIQUE (voter_key, poll_id, idempotency_key)
);
