CREATE TABLE poll_option_counter (
    option_id BIGINT PRIMARY KEY REFERENCES poll_option (id) ON DELETE CASCADE,
    vote_count BIGINT NOT NULL DEFAULT 0 CHECK (vote_count >= 0)
);

INSERT INTO poll_option_counter (option_id)
SELECT id FROM poll_option;

CREATE TABLE vote_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ballot_id BIGINT NOT NULL REFERENCES ballot (id) ON DELETE CASCADE,
    before_selection BIGINT NOT NULL,
    after_selection BIGINT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
