CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE TABLE member (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(200) NOT NULL UNIQUE,
    password_hash VARCHAR(100) NOT NULL,
    role VARCHAR(20) NOT NULL CHECK (role IN ('USER', 'ADMIN'))
);

INSERT INTO member (id, email, password_hash, role)
VALUES (1, 'admin', '{bcrypt}' || crypt('0000', gen_salt('bf', 12)), 'ADMIN');

ALTER TABLE poll ADD CONSTRAINT fk_poll_owner FOREIGN KEY (owner_id) REFERENCES member(id);
ALTER TABLE poll_option ADD CONSTRAINT uq_poll_option_order UNIQUE (poll_id, display_order);

INSERT INTO poll (id, owner_id, title, description, poll_type, max_selections, status, starts_at, ends_at)
VALUES (1, 1, '오늘, 당신의 한 표가 최애의 순간을 더 빛나게 합니다.',
        'TOP과 함께, 더 반짝이는 오늘의 선택을 만들어주세요.', 'SLAM_DUNK', 1, 'OPEN',
        clock_timestamp() - interval '1 day', clock_timestamp() + interval '7 days')
ON CONFLICT (id) DO UPDATE SET
    owner_id = EXCLUDED.owner_id,
    title = EXCLUDED.title,
    description = EXCLUDED.description,
    poll_type = EXCLUDED.poll_type,
    max_selections = EXCLUDED.max_selections,
    status = EXCLUDED.status,
    starts_at = EXCLUDED.starts_at,
    ends_at = EXCLUDED.ends_at;

INSERT INTO poll_option (poll_id, name, image_url, team, display_order) VALUES
    (1, '강백호', 'https://slamdunk-movie.jp/files/images/p_main_sakuragi.jpg', '북산 · PF', 1),
    (1, '서태웅', 'https://slamdunk-movie.jp/files/images/p_main_rukawa.jpg', '북산 · SF', 2),
    (1, '정대만', 'https://slamdunk-movie.jp/files/images/p_main_mitsui.jpg', '북산 · SG', 3),
    (1, '송태섭', 'https://slamdunk-movie.jp/files/images/p_main_miyagi.jpg', '북산 · PG', 4),
    (1, '채치수', 'https://slamdunk-movie.jp/files/images/p_main_akagi.jpg', '북산 · C', 5),
    (1, '윤대협', 'https://renote.net/files/blobs/proxy/eyJfcmFpbHMiOnsiZGF0YSI6ODUzMjY1NCwicHVyIjoiYmxvYl9pZCJ9fQ%3D%3D--926f4d837d7892c0f331deaaedf71f1bebaa237a/l1029639668.jpg', '능남 · SF', 6),
    (1, '이정환', 'https://i.pinimg.com/736x/a1/69/eb/a169eb6c223678470a15fe3e5421dd70--manga-games-kuroko.jpg', '해남 · PG', 7),
    (1, '권준호', 'https://img.online-station.net/image_content/2023/01/Kogure-Kiminobu-600x600.jpg', '북산 · SF', 8)
ON CONFLICT (poll_id, display_order) DO UPDATE SET
    name = EXCLUDED.name,
    image_url = EXCLUDED.image_url,
    team = EXCLUDED.team;

INSERT INTO poll_option_counter (option_id)
SELECT id FROM poll_option WHERE poll_id = 1
ON CONFLICT (option_id) DO NOTHING;

INSERT INTO ballot (poll_id, voter_key)
SELECT 1, lpad(to_hex(number), 64, '0') FROM generate_series(1, 50) AS number
ON CONFLICT (poll_id, voter_key) DO NOTHING;

INSERT INTO ballot_selection (ballot_id, option_id)
SELECT b.id, o.id
FROM generate_series(1, 50) AS seeded(number)
JOIN ballot b ON b.poll_id = 1 AND b.voter_key = lpad(to_hex(seeded.number), 64, '0')
JOIN poll_option o ON o.poll_id = b.poll_id AND o.display_order = CASE
    WHEN seeded.number <= 12 THEN 1
    WHEN seeded.number <= 22 THEN 2
    WHEN seeded.number <= 30 THEN 3
    WHEN seeded.number <= 36 THEN 4
    WHEN seeded.number <= 41 THEN 5
    WHEN seeded.number <= 45 THEN 6
    WHEN seeded.number <= 48 THEN 7
    ELSE 8 END
ON CONFLICT (ballot_id, option_id) DO NOTHING;

UPDATE poll_option_counter c
SET vote_count = (SELECT count(*) FROM ballot_selection s WHERE s.option_id = c.option_id)
WHERE c.option_id IN (SELECT id FROM poll_option WHERE poll_id = 1);

SELECT setval(pg_get_serial_sequence('poll', 'id'), (SELECT max(id) FROM poll));
SELECT setval(pg_get_serial_sequence('poll_option', 'id'), (SELECT max(id) FROM poll_option));
